branchName: '${issue.number}-${issue.title}'
autoCloseIssue: true
openDraftPR: true
copyIssueLabelsToPR: true
copyIssueAssigneeToPR: true

branches:
  - label: bug
    prefix: bugfix/
  - label: '*'
    prefix: feature/